name = "StructTypes"
uuid = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
authors = ["Jacob Quinn"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
